In [205]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error
import ipaddress
import glob
import os
import tensorflow as tf
import tensorflow.keras as keras
from sklearn.model_selection import train_test_split as tts      
from sklearn.preprocessing import StandardScaler as SS
from sklearn.metrics import confusion_matrix as CM 
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score as AS
from sklearn.linear_model import LinearRegression as LR
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.tree import DecisionTreeClassifier as dtc
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn import tree 

In [222]:
#DATA PROCESSING#

#Include all .csv files in directory of this code #

all_files = glob.glob("*.csv")
print(all_files)
li = []
#print(path)
data = pd.concat((pd.read_csv(f,index_col='No.') for f in all_files),ignore_index=True)

#Init Website Target#
data['Website'] = 100

#Website Target Labels and IP Addresses#
#SINGLE UP DOWN #

# (1-4) Amazon = 1
amaz_src_dest = ["18.160.17.214","18.165.77.79"] #TCP
data.loc[data['Source'] == amaz_src_dest[0],'Website'] = 1
data.loc[data['Source'] == amaz_src_dest[1],'Website'] = 1
data.loc[data['Destination'] == amaz_src_dest[0],'Website'] = 1
data.loc[data['Destination'] == amaz_src_dest[1],'Website'] = 1

# (1-5) Bing = 2
bing_src_dest = ["204.79.197.200"] #TCP
data.loc[data['Source'] == bing_src_dest[0],'Website'] = 2
data.loc[data['Destination'] == bing_src_dest[0],'Website'] = 2

# (1-4) ChatGPT = 3 
chat_src_dest = ["104.18.37.228"] # TCP
data.loc[data['Source'] == chat_src_dest[0],'Website'] = 3
data.loc[data['Destination'] == chat_src_dest[0],'Website'] = 3

#CONTINUOUS UP DOWN #
# (1-4) Discord CHAT CONTINUOUS = 4
discCHAT_src_dest = ["66.22.231.191"] # UDP
data.loc[data['Source'] == discCHAT_src_dest[0],'Website'] = 4
data.loc[data['Destination'] == discCHAT_src_dest[0],'Website'] = 4

# (1-3) Fortnite = 5
fort_src_dest = ["20.36.181.22","3.129.219.222","3.144.65.185"] # UDP
data.loc[data['Source'] == fort_src_dest[0],'Website'] = 5
data.loc[data['Source'] == fort_src_dest[1],'Website'] = 5
data.loc[data['Source'] == fort_src_dest[2],'Website'] = 5
data.loc[data['Destination'] == fort_src_dest[0],'Website'] = 5
data.loc[data['Destination'] == fort_src_dest[1],'Website'] = 5
data.loc[data['Destination'] == fort_src_dest[2],'Website'] = 5

# (1-4) Minecraft = 6 #TCP
mine_src_dest = ["209.222.115.47","104.234.169.167","31.25.11.18","31.25.11.55"]
data.loc[data['Source'] == mine_src_dest[0],'Website'] = 6
data.loc[data['Source'] == mine_src_dest[1],'Website'] = 6
data.loc[data['Source'] == mine_src_dest[2],'Website'] = 6
data.loc[data['Source'] == mine_src_dest[3],'Website'] = 6
data.loc[data['Destination'] == mine_src_dest[0],'Website'] = 6
data.loc[data['Destination'] == mine_src_dest[1],'Website'] = 6
data.loc[data['Destination'] == mine_src_dest[2],'Website'] = 6
data.loc[data['Destination'] == mine_src_dest[3],'Website'] = 6

#SINGLE DOWN #
# (1-5) Wikipedia = 0
wiki_src_dest = ["208.80.154.224"] #TCP
data.loc[data['Source'] == wiki_src_dest[0],'Website'] = 0 
data.loc[data['Destination'] == wiki_src_dest[0],'Website'] = 0 

#ryrob (1-3) = 7
ryrob_src_dest = ["172.66.40.147"] #QUIC
data.loc[data['Source'] == ryrob_src_dest[0],'Website'] = 7
data.loc[data['Destination'] == ryrob_src_dest[0],'Website'] = 7

#ugm.org (1-5) = 8
ugm_src_dest = ["13.84.36.2"] #TCP TLSv1.2
data.loc[data['Source'] == ugm_src_dest[0],'Website'] = 8
data.loc[data['Destination'] == ugm_src_dest[0],'Website'] = 8

#CONTINUOUS DOWN #
#(1-3) HULU = 9
hulu_src_dest = ["23.48.104.108", "23.48.104.112","23.48.104.110"] #TCP TLSv1.2
data.loc[data['Source'] == hulu_src_dest[0],'Website'] = 9
data.loc[data['Source'] == hulu_src_dest[1],'Website'] = 9
data.loc[data['Source'] == hulu_src_dest[2],'Website'] = 9
data.loc[data['Destination'] == hulu_src_dest[0],'Website'] = 9
data.loc[data['Destination'] == hulu_src_dest[1],'Website'] = 9
data.loc[data['Destination'] == hulu_src_dest[2],'Website'] = 9

#
data.drop(columns = ['Info'], inplace = True)
#Drop random IP addresses and Protocol
data = data.drop(data[data['Website'] == 100].index)
# data = data.drop(data[data['Protocol'] == "RTCP"].index)
#Convert IP addresses to Integers
data['Source'] = data['Source'].apply(lambda x : int(ipaddress.ip_address(x)))
data['Destination'] = data['Destination'].apply(lambda x : int(ipaddress.ip_address(x)))

#Convert Protocols to ints
#QUIC = 1
#TCP/TLS = 2
#UDP = 3 
#RTCP = 4
data.loc[data['Protocol'] == "QUIC",'Protocol'] = 1
data.loc[data['Protocol'] == "TLSv1.2",'Protocol'] = 2
data.loc[data['Protocol'] == "TLSv1.3",'Protocol'] = 2
data.loc[data['Protocol'] == "TCP",'Protocol'] = 2
data.loc[data['Protocol'] == "UDP",'Protocol'] = 3
data.loc[data['Protocol'] == "RTCP",'Protocol'] = 4

#Drop SRC DEST #
data.drop(columns = ['Source','Destination'], inplace = True)
data

['fortnite1_continuousupdown.csv', 'Wikipedia2_singledown.csv', 'hulu3_continuous-download.csv', 'Wikipedia5_singledown.csv', 'chatgpt3_singleupdown.csv', 'ryrod2_singledown.csv', 'ryrod3_singledown.csv', 'amazon1_singleupdown.csv', 'bing3_singleupdown.csv', 'Wikipedia4_singledown.csv', 'Wikipedia3_singledown.csv', 'discord3_continuousupdown.csv', 'Wikipedia1_singledown.csv', 'amazon4_singleupdown.csv', 'ryrod1_singledown.csv', 'chatgpt2_singleupdown.csv', 'bing_singleupdown.csv', 'chatgpt_singleupdown.csv', 'bing2_singleupdown.csv', 'discord2_continuousupdown.csv', 'minecraft1_continuousupdown.csv', 'minecraft4_continuousupdown.csv', 'ugm5_singledown.csv', 'minecraft2_continuousupdown.csv', 'bing5_singleupdown.csv', 'discord1_continuousupdown.csv', 'discord4_continuousupdown.csv', 'ugm2_singledown.csv', 'ugm3_singledown.csv', 'fortnite3_continuousupdown.csv', 'hulu2_continuous-download.csv', 'ugm4_singledown.csv', 'amazon3_singleupdown.csv', 'bing4_singleupdown.csv', 'hulu1_continuous

Time Protocol  Length  Website
0      0.000000        3      97        5
1      0.010276        3      82        5
2      0.048486        3      83        5
3      0.050166        3     120        5
4      0.076227        3      82        5
...         ...      ...     ...      ...
28173  6.244447        3     108        5
28174  6.250256        3      82        5
28175  6.280475        3     201        5
28176  6.315326        3      83        5
28177  6.346554        3      82        5

[27971 rows x 4 columns]

In [232]:
#DATA SPLIT#
X = data.iloc[:,0:3]
y = data.iloc[:,3]


X_train, X_test, y_train, y_test = tts(X,y,random_state=17, test_size = 0.33)
 
# scaler = SS()  
#  # Don't cheat - fit only on training data
# scaler.fit(X_train) 

# X_train = scaler.transform(X_train)  
#  # apply same transformation to test data
# X_test = scaler.transform(X_test)  
#X_test.reshape(-1,5)


y

0        5
1        5
2        5
3        5
4        5
        ..
28173    5
28174    5
28175    5
28176    5
28177    5
Name: Website, Length: 27971, dtype: int64

In [247]:
#Decision TREE Classifier#
tree = dtc()
tree.fit(X_train,y_train)
y_pred = tree.predict(X_test)
print("DTC SCORE",tree.score(X_train, y_train))
CM(y_test,y_pred)

DTC SCORE 0.9999466382070438


array([[ 146,   17,   27,   10,    0,    0,   31,    0,   30,   13],
       [   5,  391,   18,   21,    0,    0,   16,    0,   10,   20],
       [  31,   24, 1907,   23,    0,    0,   81,    0,   33,   38],
       [  13,   24,   16,  376,    0,    0,   13,    0,    6,   26],
       [   0,    0,    0,    0,  698,   47,    0,    9,    0,    0],
       [   0,    0,    0,    0,   43,  645,    0,   10,    0,    0],
       [  38,   18,   74,   28,    0,    0,  995,    0,   42,   44],
       [   0,    0,    0,    0,   10,    5,    0, 1310,    0,    0],
       [  38,    7,   36,    7,    0,    0,   27,    0,  774,    7],
       [  12,   19,   26,   18,    0,    0,   25,    0,    9,  844]])

In [248]:
#DTC#
#['Wikipedia','Amazon','Bing','Chat','Discord','Fortnite','Minecraft','ryrob','ugm','hulu']
print(classification_report(y_test,y_pred,target_names= ['Wikipedia','Amazon','Bing','Chat','Discord','Fortnite','Minecraft','ryrob','ugm','hulu']))
features = pd.DataFrame(tree.feature_importances_,index = X.columns)
features

              precision    recall  f1-score   support

   Wikipedia       0.52      0.53      0.52       274
      Amazon       0.78      0.81      0.80       481
        Bing       0.91      0.89      0.90      2137
        Chat       0.78      0.79      0.79       474
     Discord       0.93      0.93      0.93       754
    Fortnite       0.93      0.92      0.92       698
   Minecraft       0.84      0.80      0.82      1239
       ryrob       0.99      0.99      0.99      1325
         ugm       0.86      0.86      0.86       896
        hulu       0.85      0.89      0.87       953

    accuracy                           0.88      9231
   macro avg       0.84      0.84      0.84      9231
weighted avg       0.88      0.88      0.88      9231



0
Time      0.482039
Protocol  0.236851
Length    0.281109

In [245]:
#Random Forests Classifier#
#Split AGAIN #
Xtrain,Xtest,ytrain,ytest = tts(X,y,test_size=0.33, random_state = 146)

#do the stuff
rfc = RFC(random_state = 146, n_estimators = 100, max_depth = 18)
rfc.fit(Xtrain, ytrain)
y_pred = rfc.predict(Xtest)
print("RFC SCORE",rfc.score(Xtrain, ytrain))
print(CM(ytest,y_pred))
print(classification_report(ytest,y_pred,target_names=['Wikipedia','Amazon','Bing','Chat','Discord','Fortnite','Minecraft','ryrob','ugm','hulu']))


RFC SCORE 0.9737459978655283
[[ 117   19   57    8    0    0   42    0   36   15]
 [   5  412   24   16    0    0   19    0    5   24]
 [  15   27 1915    7    0    0   89    0   32   29]
 [   4   24   19  404    0    0   22    0    3   46]
 [   0    0    0    0  688   33    0    1    0    0]
 [   0    0    0    0   26  675    0    4    0    0]
 [  19   11   80    9    0    0 1037    0   42   45]
 [   0    0    0    0    4    4    0 1271    0    0]
 [   8   12   45    3    0    0   37    0  745    4]
 [   8   18   47   13    0    0   46    0    2  859]]
              precision    recall  f1-score   support

   Wikipedia       0.66      0.40      0.50       294
      Amazon       0.79      0.82      0.80       505
        Bing       0.88      0.91      0.89      2114
        Chat       0.88      0.77      0.82       522
     Discord       0.96      0.95      0.96       722
    Fortnite       0.95      0.96      0.95       705
   Minecraft       0.80      0.83      0.82      1243
       

In [ ]:
#KNN NEED DONE #
for i in range(2,10):
    knn = KNN(n_neighbors = i)

    knn.fit(X_train,y_train)
    y_pred = knn.predict(x_test)
    acc = AS(y_pred,y_test)
    print("accuracy{i}:",acc)

In [225]:
#TensorFlow Setup DISREGARD ALL BELOW# 

features = data.drop(columns='Website').to_numpy()
labels = data['Website'].to_numpy()
features = np.expand_dims(features,-1)
labels = np.expand_dims(labels,-1)
#x_tensor = tf.convert_to_tensor(features, dtype=tf.int64) 
#y_tensor = tf.convert_to_tensor(labels, dtype=tf.int64) 
x_train, x_test,y_train,y_test = tts(features,labels,test_size=0.33,shuffle=True)
x_tensor = tf.convert_to_tensor(x_train, dtype=tf.int64) 
y_tensor = tf.convert_to_tensor(y_train, dtype=tf.int64) 
x_tensor
y_tensor



<tf.Tensor: shape=(18740, 1), dtype=int64, numpy=
array([[1],
       [4],
       [1],
       ...,
       [2],
       [8],
       [0]])>

In [200]:
model = tf.keras.Sequential([
    #keras.layers.Dense(len(x_tensor)),
    keras.layers.Dense(f),
    keras.layers.Dense(512, activation=tf.nn.relu),
    keras.layers.Dense(256, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10,activation=tf.nn.softmax)
])
# model.add(tf.keras.layers.Dense(1024))
# model.add(tf.keras.layers.Dense(units=512, activation='relu'))
# model.add(tf.keras.layers.Dense(units=256, activation='relu'))
# model.add(tf.keras.layers.Dense(units=128, activation='relu'))
# model.add(tf.keras.layers.Dense(units=10, activation='softmax'))
# model = tf.keras.Sequential()
# model.add(tf.keras.layers.Dense(units=6, activation='relu', input_shape=[6,]))
# model.add(tf.keras.layers.Dense(units=20, activation='relu'))
# model.add(tf.keras.layers.Dense(units=25, activation='relu'))
# model.add(tf.keras.layers.Dense(units=20, activation='relu'))
# model.add(tf.keras.layers.Dense(units=1, activation='relu'))
    # keras.layers.Dense(x_tensor,kernel_regularizer=tf.keras.regularizers(0.1)),
    # keras.layers.Dense(512, activation=tf.nn.relu, kernel_regularizer=tf.kerars.regularizers(0.1)),
    # keras.layers.Dense(256, activation=tf.nn.relu, kernel_regularizer=tf.kerars.regularizers(0.1)),
    # keras.layers.Dense(128, activation=tf.nn.relu, kernel_regularizer=tf.kerars.regularizers(0.1)),
    # keras.layers.Dense(10,activation=tf.nn.softmax)

model.compile(optimizer=tf.compat.v1.train.AdamOptimizer(learning_rate=0.001),
            loss ='mse',
            metrics=['accuracy'])
# model.compile(optimizer = 'adam', loss = "mse",metrics=['accuracy'])
#model.summary()
history= model.fit(x_tensor,y_tensor,batch_size = 100,epochs = 400)

Epoch 1/400


InvalidArgumentError: Graph execution error:

Detected at node 'gradient_tape/mean_squared_error/BroadcastGradientArgs' defined at (most recent call last):
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/traitlets/config/application.py", line 992, in launch_instance
      app.start()
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 701, in start
      self.io_loop.start()
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 195, in start
      self.asyncio_loop.run_forever()
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
      await self.process_one()
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 523, in process_one
      await dispatch(*args)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
      await result
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
      reply_content = await reply_content
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
      res = shell.run_cell(
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3009, in run_cell
      result = self._run_cell(
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3064, in _run_cell
      result = runner(coro)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3269, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3448, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/var/folders/th/t0lfd8fx2dd8yyzcv6_91y7c0000gn/T/ipykernel_16196/4270130018.py", line 31, in <module>
      history= model.fit(x_tensor,y_tensor,batch_size = 100,epochs = 400)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/keras/engine/training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/keras/engine/training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/keras/engine/training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/keras/engine/training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/keras/engine/training.py", line 997, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/Users/coltonturner/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/keras/optimizers/optimizer_v1.py", line 872, in minimize
      grads = tape.gradient(loss, var_list, grad_loss)
Node: 'gradient_tape/mean_squared_error/BroadcastGradientArgs'
Incompatible shapes: [100,5,10] vs. [100,1]
	 [[{{node gradient_tape/mean_squared_error/BroadcastGradientArgs}}]] [Op:__inference_train_function_329426]

In [226]:
#Model Fitting
inputs = tf.keras.layers.Input(shape=(x_tensor.shape[1],x_tensor.shape[2]))
rnn_out = tf.keras.layers.SimpleRNN(32)(inputs)
outputs = tf.keras.layers.Dense(1)(rnn_out)

model = tf.keras.Model(inputs=inputs,outputs=[outputs])
model.compile(optimizer = 'adam', loss = "cross",metrics=['accuracy'])
model.summary()
history= model.fit(x_tensor,y_tensor,batch_size = 2,epochs = 4)

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 3, 1)]            0         
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_101 (Dense)           (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________
Epoch 1/4
9370/9370 [==============================] - 13s 1ms/step - loss: 7.2564 - accuracy: 0.0535
Epoch 2/4
9370/9370 [==============================] - 13s 1ms/step - loss: 7.1583 - accuracy: 0.0535
Epoch 3/4
9370/9370 [==============================] - 12s 1ms/step - loss: 7.0488 - accuracy: 0.0535
Epoch 4/4
9370/